apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-br1-vlan-trunk 
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: '' 
  desiredState:
    interfaces:
    - name: bond2
      state: up
      type: bond
      link-aggregation:
        mode: 802.3ad
        port:
          - eno1
          - eno2
      ipv4:
        enabled: false
    - name: ovs-br1 
      description: |-
        A dedicated OVS bridge with bond2 as a port
        allowing all VLANs and untagged traffic
      type: ovs-bridge
      state: up
      bridge:
        options:
          stp: true
        port:
        - name: bond2 
    ovn:
      bridge-mappings:
      - localnet: vlan-505
        bridge: ovs-br1 
        state: present 
      - localnet: vlan-506
        bridge: ovs-br1 
        state: present         
      - localnet: vlan-10
        bridge: ovs-br1 
        state: present 

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: VLAN 505 connection for VMs
  name: vlan-505
  namespace: metal-example
spec:
  config: |-
    {
      "cniVersion": "0.3.1", 
      "name": "vlan-505", 
      "type": "ovn-k8s-cni-overlay", 
      "topology": "localnet", 
      "netAttachDefName": "metal-example/vlan-505",
      "vlanID": 505,
      "ipam": {}
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: VLAN 10 connection for VMs
  name: vlan-10
  namespace: test-vm
spec:
  config: |-
    {
      "cniVersion": "0.3.1", 
      "name": "vlan-10", 
      "type": "ovn-k8s-cni-overlay", 
      "topology": "localnet", 
      "netAttachDefName": "test-vm/vlan-10",
      "vlanID": 10,
      "ipam": {}
    }


apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: VLAN 506 connection for VMs
  name: vlan-506
  namespace: test-vm
spec:
  config: |-
    {
      "cniVersion": "0.3.1", 
      "name": "vlan-506", 
      "type": "ovn-k8s-cni-overlay", 
      "topology": "localnet", 
      "netAttachDefName": "test-vm/vlan-506",
      "vlanID": 506,
      "ipam": {}
    }
